### ISSUE TITLE
Support for Per-Repository YAML Configuration Files

### ISSUE THREAD

**Issue by srtab** [srtab/daiv#51]
## **Description**

I would like to propose the addition of a feature that allows each repository integrated with DAIV to include its own YAML configuration file (e.g., `.daiv.yml`) at the root of the repository. This file would enable repository maintainers to customize DAIV's behavior on a per-repository basis, providing greater flexibility and control over how DAIV interacts with their codebase.

## **Proposed Functionality**

The per-repository YAML configuration file would support the following configurations:

### **1. Repository Metadata**

- **`default_branch`**
  - *Description*: Specify the default branch that DAIV should use for its operations, such as code generation, pull requests, and updates.
  - *Example*:
    ```yaml
    default_branch: "main"
    ```

- **`repository_description`**
  - *Description*: Provide context or a detailed description of the repository to help DAIV better understand the project's purpose and domain.
  - *Example*:
    ```yaml
    repository_description: "A microservice for handling user authentication and authorization."
    ```

### **2. Feature Flags and Toggles**

- **`features`**
  - *Description*: Enable or disable DAIV's main features for the repository.
  - *Options*:
    - **`code_review_automation`**: `true` or `false`
    - **`issue_implementation`**: `true` or `false`
    - **`pipeline_fixes`**: `true` or `false`
  - *Example*:
    ```yaml
    features:
      code_review_automation: true
      issue_implementation: false
      pipeline_fixes: true
    ```

- **`experimental_features`**
  - *Description*: Opt-in to new or beta features that DAIV offers.
  - *Example*:
    ```yaml
    experimental_features:
      advanced_debugging: false
    ```

### **3. Codebase Restrictions**

- **`blocked_paths`**
  - *Description*: Define directories or files where DAIV should not make changes.
  - *Example*:
    ```yaml
    blocked_paths:
      - "/config/"
      - "/scripts/deployment.sh"
      - "/secrets/"
    ```

- **`ignored_file_types`**
  - *Description*: Specify file extensions or patterns that DAIV should ignore during its operations.
  - *Example*:
    ```yaml
    ignored_file_types:
      - "*.md"
      - "*.yaml"
      - "*.log"
    ```

### **5. Issue and Pull Request Management**

- **`branch_name_pattern`**
  - *Description*: Define the naming convention for branches that DAIV creates.
  - *Example*:
    ```yaml
    branch_name_pattern: "daiv/{issue_number}-{short_description}"
    ```

### **13. Localization and Internationalization**

- **`language_settings`**
  - *Description*: Set language preferences for code comments, documentation, and communications.
  - *Options*:
    - **`primary_language`**: The main language DAIV should use.
  - *Example*:
    ```yaml
    language_settings:
      primary_language: "en"
    ```

- **`locale`**
  - *Description*: Set locale-specific settings like date and number formats.
  - *Example*:
    ```yaml
    locale: "en_US"
    ```

## **Example Configuration File**

Here is how a `.daiv.yml` file might look with these settings:

```yaml
# daiv repository configuration file

# 1. Repository metadata
default_branch: "main"
repository_description: "A microservice for handling user authentication and authorization."

# 2. Feature flags and toggles
features:
  code_review_automation: true
  issue_implementation: false
  pipeline_fixes: true

experimental_features:
  advanced_debugging: false

# 3. Codebase restrictions
blocked_paths:
  - "/config/"
  - "/scripts/deployment.sh"
  - "/secrets/"
ignored_file_types:
  - "*.md"
  - "*.yaml"
  - "*.log"

# 5. Issue and pull request management
branch_name_pattern: "daiv/{issue_number}-{short_description}"

# 13. Localization and internationalization
language_settings:
  primary_language: "en"

locale: "en_US"
```

## **Benefits**

- **Customization**: Allows teams to tailor DAIV's behavior to their specific needs and workflows.
- **Flexibility**: Enables per-repository configurations without affecting global settings.
- **Control**: Gives repository maintainers the ability to manage which features are active and how DAIV interacts with their codebase.
- **Safety**: Prevents DAIV from making unintended changes to sensitive parts of the codebase.

## **Implementation Considerations**

- **Configuration Parsing**: DAIV should parse the `.daiv.yml` file upon interacting with the repository and adjust its behavior accordingly.
- **Override Mechanism**: Repository configurations should override global settings where applicable.
- **Validation**: Implement schema validation to ensure the configuration file is correctly formatted and contains valid values.
- **Error Handling**: Provide clear error messages if the configuration file is missing or contains invalid entries.
- **Security**: Avoid storing sensitive information (like API keys) in the configuration file to prevent security risks.
- **Documentation**: Update DAIV's documentation to include guidelines on how to create and manage the `.daiv.yml` file.

## **Request**

Implementing support for per-repository YAML configuration files would significantly enhance DAIV's usability and adoption. It would empower teams to customize DAIV's functionalities to better suit their development processes and policies.

I kindly request that this feature be considered for future development. I'm happy to provide additional details or assist with testing if needed.
